<?php foreach ($indexes AS $index): ?>
<div class="row">
    <div class="large-6 columns">
    <a href="<?php echo $this->url('elasticsearchexplorer/search/searchindex', array('searchindex' => $index['name'])); ?>"><h2><?php echo $index['name']; ?></h2></a>
        <table>
            <tr>
                <td><strong>Total docs</strong></td>
                <td><?php echo $index['total_docs']; ?></td>
            </tr>
            <tr>
                <td><strong>Total size</strong></td>
                <td><?php echo $index['total_size']; ?></td>
            </tr>
        </table>
    </div>
</div>
<?php endforeach; ?>
