<?php foreach ($indexes AS $index): ?>
<div class="row">
    <div class="large-6 columns">
        <h2>
            <a href="<?php echo $this->url('elasticsearchexplorer/search/searchindex', array('searchindex' => $index['name'])); ?>">
                <?php echo $index['name']; ?>
            </a>
        </h2>
        <table>
            <tr>
                <td><strong><?php echo $this->translate('Total docs', __NAMESPACE__); ?></strong></td>
                <td><?php echo $index['total_docs']; ?></td>
            </tr>
            <tr>
                <td><strong><?php echo $this->translate('Total size', __NAMESPACE__); ?></strong></td>
                <td><?php echo $index['total_size']; ?></td>
            </tr>
        </table>
    </div>
</div>
<?php endforeach; ?>
