<?php $this->headTitle()->append('Plugins'); ?>

<?php if ($this->plugins): ?>
<div class="col-sm-6">
    <h2><?php echo $this->translate('Plugins', __NAMESPACE__); ?></h2>
    <table class="table">
        <tbody>
        <?php foreach ($this->plugins AS $plugin): ?>
            <tr>
                <td><a href="http://<?php echo $this->hosts . $plugin['url']; ?>" target="_blank"><strong><?php echo $plugin['name']; ?></strong></a></td>
                <td><?php echo $plugin['description']; ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php endif; ?>
