<?php $this->formRow()->setTranslatorTextDomain(__NAMESPACE__); ?>

<?php if ($this->indexes): ?>
    <?php echo $this->form()->openTag($form); ?>

        <div class="row">
            <div class="large-12 columns">
                <?php 
                    $searchIndexElement = $form->get('searchindex');
                    $form->updateValueOptions($searchIndexElement, $this->indexes, $this->searchindex);
                    echo $this->formRow($searchIndexElement);
                ?>
            </div>
        </div>

        <div class="row<?php if (!$this->searchindex) { echo ' invisible'; } ?>">
            <div class="large-12 columns">
                <?php 
                    $searchTypeElement = $form->get('searchtype');
                    $form->updateValueOptions($searchTypeElement, $this->types, $this->searchtype);
                    echo $this->formRow($searchTypeElement);
                ?>
            </div>
        </div>

        <div class="row<?php if (!$this->searchtype) { echo ' invisible'; } ?>">
            <div class="large-12 columns">
                <?php 
                    $searchFieldElement = $form->get('searchfield');
                    $form->updateValueOptions($searchFieldElement, $this->fields, $this->searchfield);
                    echo $this->formLabel()->openTag($searchFieldElement);
                    echo $this->translate($searchFieldElement->getLabel(), __NAMESPACE__);
                    echo '&nbsp;<a href="#" data-reveal-id="modalFields"><span class="fi-info"></span></a>';
                    echo $this->formSelect($searchFieldElement);
                    echo $this->formLabel()->closeTag();
                ?>

                <div id="modalFields" class="reveal-modal" data-reveal>
                    <h5><?php echo $this->translate('Fields', __NAMESPACE__); ?></h5>
                    <table>
                        <thead>
                            <tr>
                                <th><?php echo $this->translate('Name', __NAMESPACE__); ?></th>
                                <th><?php echo $this->translate('Type', __NAMESPACE__); ?></th>
                                <th><?php echo $this->translate('Index', __NAMESPACE__); ?></th>
                            </tr>
                        </thead>
                        <?php foreach ($this->fields AS $field): ?>
                        <tr>
                            <td><?php echo $field['name']; ?></td>
                            <td><?php echo $field['type']; ?></td>
                            <td><?php echo $field['index']; ?></td>
                        </tr>
                        <?php endforeach; ?>
                    </table>
                    <a class="close-reveal-modal">&#215;</a>
                </div>
            </div>
        </div>

        <div class="row<?php if (!$this->searchtype) { echo ' invisible'; } ?>">
            <div class="large-12 columns">
                <?php 
                    $searchTermElement = $form->get('searchterm');
                    $searchTermElement->setValue($this->searchterm);
                    echo $this->formRow($searchTermElement);
                ?>
            </div>
        </div>

        <div class="row<?php if (!$this->searchtype) { echo ' invisible'; } ?>">
            <div class="large-12 columns">
                <?php echo $this->formButton()->render($form->get('submit'), $this->translate('Start search', __NAMESPACE__)); ?>
            </div>
        </div>

    <?php echo $this->form()->closeTag(); ?>
<?php endif; ?>

<?php if ($this->results && count($this->results)): ?>
    <?php foreach ($this->results AS $result): ?>
    <div class="row search-row">
        <div class="large-12 columns">
            <table>
            <?php foreach ($result['_source'] AS $resultSourceKey => $resultSource): ?>
                <tr>
                    <td><strong><?php echo $resultSourceKey; ?></strong></td>
                    <td><?php echo $resultSource; ?></td>
                </tr>
            <?php endforeach; ?>
            </table>
        </div>
    </div>
    <?php endforeach; ?>
<?php endif; ?>
