<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>ElasticsearchExplorer</title>
        <meta name="robots" content="noindex,nofollow">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <?php
        echo $this->headLink()->appendStylesheet($this->basePath().'/elasticsearch-explorer-public/css/normalize.css');
        echo $this->headLink()->appendStylesheet($this->basePath().'/elasticsearch-explorer-public/css/foundation.min.css');
        echo $this->headLink()->appendStylesheet($this->basePath().'/elasticsearch-explorer-public/icons/foundation-icons.css');
        echo $this->headLink()->appendStylesheet($this->basePath().'/elasticsearch-explorer-public/css/main.css');
        ?>
    </head>
    <body>
        <div class="contain-to-grid sticky">
            <nav class="top-bar" data-topbar role="navigation" data-options="sticky_on: large">
                <ul class="title-area">
                    <li class="name"></li>
                    <li class="toggle-topbar menu-icon"><a href="#"><span><?php echo $this->translate('Menu', __NAMESPACE__); ?></span></a></li>
                </ul>

                <section class="top-bar-section">
                    <ul class="left">
                        <li>
                            <a href="<?php echo $this->url('elasticsearchexplorer'); ?>">
                                <span class="fi-home"></span>
                                <?php echo $this->translate('Home', __NAMESPACE__); ?>
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('elasticsearchexplorer/search'); ?>">
                                <span class="fi-magnifying-glass"></span>
                                <?php echo $this->translate('Search', __NAMESPACE__); ?>
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('elasticsearchexplorer/config'); ?>">
                                <span class="fi-widget"></span>
                                <?php echo $this->translate('Configuration', __NAMESPACE__); ?>
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('elasticsearchexplorer/plugins'); ?>">
                                <span class="fi-puzzle"></span>
                                <?php echo $this->translate('Plugins', __NAMESPACE__); ?>
                            </a>
                        </li>
                        <li>
                            <a href="https://github.com/dan-lyn/ElasticsearchExplorerModule" target="_blank">
                                <span class="fi-social-github"></span>
                                <?php echo $this->translate('GitHub', __NAMESPACE__); ?>
                            </a>
                        </li>
                    </ul>
                </section>
            </nav>
        </div>

        <div class="content">
            <?php echo $this->content; ?>
        </div>

        <?php
        echo $this->headScript()->appendFile($this->basePath().'/elasticsearch-explorer-public/js/vendor/jquery.js');
        echo $this->headScript()->appendFile($this->basePath().'/elasticsearch-explorer-public/js/vendor/jquery.cookie.js');
        echo $this->headScript()->appendFile($this->basePath().'/elasticsearch-explorer-public/js/vendor/modernizr.js');
        echo $this->headScript()->appendFile($this->basePath().'/elasticsearch-explorer-public/js/vendor/placeholder.js');
        echo $this->headScript()->appendFile($this->basePath().'/elasticsearch-explorer-public/js/vendor/fastclick.js');
        echo $this->headScript()->appendFile($this->basePath().'/elasticsearch-explorer-public/js/foundation.min.js');
        echo $this->headScript()->appendFile($this->basePath().'/elasticsearch-explorer-public/js/main.min.js');
        echo $this->headScript()->appendFile($this->basePath().'/elasticsearch-explorer-public/js/search.min.js');
        ?>
    </body>
</html>
