<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>ElasticsearchExplorer</title>
        <meta name="robots" content="noindex,nofollow">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <?php
        echo $this->headLink()->appendStylesheet($this->basePath().'/elasticsearch-explorer-public/css/bootstrap.min.css');
        echo $this->headLink()->appendStylesheet($this->basePath().'/elasticsearch-explorer-public/css/bootstrap-theme.min.css');
        echo $this->headLink()->appendStylesheet($this->basePath().'/elasticsearch-explorer-public/css/font-awesome.min.css');
        echo $this->headLink()->appendStylesheet($this->basePath().'/elasticsearch-explorer-public/css/main.css');
        ?>
    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="<?php echo $this->url('elasticsearchexplorer'); ?>">
                                <span class="fa fa-home"></span>
                                <?php echo $this->translate('Home', __NAMESPACE__); ?>
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('elasticsearchexplorer/search'); ?>">
                                <span class="fa fa-search"></span>
                                <?php echo $this->translate('Search', __NAMESPACE__); ?>
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('elasticsearchexplorer/config'); ?>">
                                <span class="fa fa-cog"></span>
                                <?php echo $this->translate('Configuration', __NAMESPACE__); ?>
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('elasticsearchexplorer/plugins'); ?>">
                                <span class="fa fa-puzzle-piece"></span>
                                <?php echo $this->translate('Plugins', __NAMESPACE__); ?>
                            </a>
                        </li>
                        <li>
                            <a href="https://github.com/dan-lyn/ElasticsearchExplorerModule" target="_blank">
                                <span class="fa fa-github"></span>
                                <?php echo $this->translate('GitHub', __NAMESPACE__); ?>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container">
            <?php echo $this->content; ?>
        </div>

        <?php
        echo $this->headScript()->appendFile($this->basePath().'/elasticsearch-explorer-public/js/vendor/jquery.js');
        echo $this->headScript()->appendFile($this->basePath().'/elasticsearch-explorer-public/js/vendor/jquery.cookie.js');
        echo $this->headScript()->appendFile($this->basePath().'/elasticsearch-explorer-public/js/bootstrap.min.js');
        echo $this->headScript()->appendFile($this->basePath().'/elasticsearch-explorer-public/js/search.min.js');
        ?>
    </body>
</html>
